### PR TITLE
Enh/webserver production

### PR DESCRIPTION
**Pull request by jonaskau**
lets merge

### CODE REVIEW

**Comment by frzifus** [comment]
That's not a problem. You just have to set the appropriate host entry.
`echo "localhost      127.0.0.1:5000" > /etc/hosts`
Done :+1:

**Comment by Paeti** [comment]
Windows Not Unix

**Comment by frzifus** [comment]
right, it would also work under unix. but it was intended for GNU/Linux.
Under windows (NT8+) it shouldn't be a problem either. Just type into the powershell and change the path to `%windir%\system32\drivers\etc\hosts`.

**Comment by aiufeh** [comment]
> Windows Not Unix

Did you mean `Windows is not Unix`? Thats damn right.

**Comment by Paeti** [comment]
@frzifus the problem is that on windows docker runs in a kind of virtual maschine. so if you publish a port through the docker-compose it is published on the virtual maschine not the host. so if you use "docker-maschine ip" you can use this ip:5000 to see the website.
with "windows not unix" i meant that on windows it would be another path (unlike on unix based systems) and that i was not shure if windows has this kind of file.
on my laptop (linux) it worked without changing the /etc/hosts.

**Comment by frzifus** [comment]
Are you sure? There are several Unix systems where the host entries are at a different location.
Regardless of that i have just researched... adding ports is not supported. So it would be very bad if this would be in your host file.

> Did not work with "localhost" on my system. But it works fine when you enter :5000 in you internet browser. Good job!

So that doesn't work as described here, does it? An ip is needed `container_ip:5000`.

Then you could make your entry like this `echo "localhost $(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $containerNameOrId)" >> /etc/hosts`.

**Pull request merged**
